---
AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with IAM role for Cognito Identity operations

Parameters:
  EntraTenantId:
    Type: String
    Description: Azure Entra Tenant ID
    AllowedPattern: '[0-9a-fA-F-]{36}'
  Audience:
    Type: String
    Description: Audience for the identity token
    Default: 'api://AzureADTokenExchange'
  AwsParametersAndSecretsLayerVersion:
    Type: Number
    Description: version number
    Default: 22

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: IdentityToken
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sts:GetWebIdentityToken
                Resource: '*'
                Condition:
                  StringEquals:
                    ForAnyValue: true
                    sts:IdentityTokenAudience: !Ref Audience
                  NumericLessThanEquals:
                    sts:DurationSeconds: 300

  PythonLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-function'
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Layers:
        - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:AWS-Parameters-and-Secrets-Lambda-Extension:${AwsParametersAndSecretsLayerVersion}'
      Code:
        ZipFile: |
          # Placeholder - actual code deployed via GitHub Actions
          def handler(event, context):
              return {'statusCode': 200, 'body': 'Placeholder'}
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          ENTRA_TENANT_ID: !Ref EntraTenantId

Outputs:
  LambdaFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt PythonLambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'
  
  LambdaFunctionName:
    Description: Lambda function name
    Value: !Ref PythonLambdaFunction
    Export:
      Name: !Sub '${AWS::StackName}-FunctionName'
  
  LambdaExecutionRoleArn:
    Description: Lambda execution role ARN
    Value: !GetAtt LambdaExecutionRole.Arn